build: off
environment:
  nodejs_version: "10.4.0"
image:
  - Visual Studio 2017
branches:
  only:
    - master
    - dev
install:
  - node --version
  - npm --version
  - npm install
configuration: Release
before_test:
  - git submodule update --recursive --remote
  - tsc -v
  - npm run tsc
test_script:
  - npm test
on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/DiscordHooks/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL